sudo: true
service:
  - docker

install:
  ## GO
  # Install dev env
  - make dev@dk.go.install
  # Install test env
  - make test@go.install

  ## NPM
  # Install dev env
  - make dev@dk.npm.install

script:
  ## GO
  - make test@go.run-cover

  ## NPM
  # Run build for prod
  - make dev@npm.run-prod

notifications:
  email:
    - cifren@msn.com
