version: "3.6"

services:
  go:
    image: ghyt-api:latest
    build: .
    env_file:
      - .env.local
    ports:
     - "5000:9001"
    volumes:
      - ./:/go
    command: CompileDaemon --build="go build main.go" --command=./main

  ngrok:
    image: wernight/ngrok
