version: "3.6"

services:
  go:
    image: golang:1.12.15
    env_file:
      - .env.local
    ports:
     - "5000:9001"
    volumes:
      - ./:/www
      - ./bin:/go/bin
      - /tmp/go/pkg:/go/pkg
    command: CompileDaemon --build="go build main.go" --command=./main
    working_dir: /www

  ngrok:
    image: wernight/ngrok

  npm:
    image: npm:latest
    build:
      context: ./docker
      dockerfile: Dockerfile-npm
    volumes:
      - ./:/home/node/app
    environment:
      - NODE_ENV=developpment
      # PROD server
      - PORT=8081
    ports:
      # Webpack dev server
      - "3005:8080"
      # Npm start webserver
      - "3006:8081"
