version: "3.6"

services:
  go:
    image: ghyt-api:latest
    build:
      context: ./docker
      dockerfile: Dockerfile-go
    env_file:
      - .env.local
    ports:
     - "5000:9001"
    volumes:
      - ./:/go
    command: CompileDaemon --build="go build main.go" --command=./main

  ngrok:
    image: wernight/ngrok

  npm:
    image: npm:latest
    build:
      context: ./docker
      dockerfile: Dockerfile-npm
    volumes:
      - ./resources:/home/node/app
    environment:
      - NODE_ENV=developpment
    ports:
      - "3005:8080"
