version: "3.6"

services:
  go:
    image: ghyt-api:latest
    build: .
    ports:
     - "5000:9001"
    volumes:
      - ./:/go
    command: ["go", "run", "main.go"]
    # For hot-reload, it is not working for now
    # command: ["gin", "--port", "9000", "--appPort", "9001", "run", "main.go"]
    environment:
      GOPATH: "/go/vendor"

  ngrok:
    image: wernight/ngrok
